# Generated by Django 2.1.3 on 2018-12-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_auto_20181204_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='inSource',
            field=models.BooleanField(null=True),
        ),
    ]
