# Generated by Django 2.1.3 on 2018-12-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=15)),
                ('FirbaseID', models.CharField(max_length=20)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.Directory')),
            ],
        ),
    ]
