# Generated by Django 2.1.3 on 2018-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_auto_20181204_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='inSource',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
