# Generated by Django 2.1.3 on 2018-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0005_auto_20181204_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Parent',
        ),
        migrations.AddField(
            model_name='directory',
            name='ChildrenFiles',
            field=models.ManyToManyField(blank=True, null=True, to='ide.File'),
        ),
        migrations.AddField(
            model_name='directory',
            name='ChildrenFolder',
            field=models.ManyToManyField(blank=True, null=True, related_name='_directory_ChildrenFolder_+', to='ide.Directory'),
        ),
    ]
