# Generated by Django 2.1.3 on 2018-12-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0006_auto_20181205_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='ChildrenFolder',
        ),
        migrations.AddField(
            model_name='directory',
            name='ChildrenFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ide.Directory'),
        ),
    ]
