# Generated by Django 2.1 on 2018-10-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181014_2241'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
