# Generated by Django 2.1 on 2018-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20181014_2241'),
        ('dashboard', '0002_auto_20181014_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Key', models.CharField(max_length=6)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Created', models.DateField(auto_now=True)),
                ('LastModified', models.DateField(auto_now=True)),
                ('Contributor', models.ManyToManyField(to='accounts.Contributor')),
            ],
        ),
    ]
