# Generated by Django 2.1 on 2018-10-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Contributor',
            new_name='Developers',
        ),
    ]
