# Generated by Django 2.1.3 on 2018-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='FirebaseID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
