# Generated by Django 2.1 on 2018-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='Project',
        ),
        migrations.AddField(
            model_name='contributor',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
