# Generated by Django 2.1 on 2018-10-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181014_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='isOwner',
        ),
    ]
